#开启端口号
server:
  port: 6655

#启用feign支持
feign:
  hystrix:
    enabled: true
#在nacos服务集群进行注册
spring:
  application:
    name: fresh-system-po
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.100.43:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  #配置mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.94.100.43:3306/supplychain?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
    suffix: .html
  jackson:
    # 如果使用字符串星表示用这行格式
    date-format: yyyy-MM-dd
    # 设置为东八区时间
    timezone: GMT+8
    # 想要值为2016-01-01
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
#配置MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aaa.fresh.pojo
  configuration:
    lazy-loading-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
logging:
  level:
    com:
      aaa:
        fresh:
          mapper: trace
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

